version: '3.8'

services:
  next-arch-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-arch-demo
    ports:
      - '${HOST_PORT:-3000}:${CONTAINER_PORT:-3000}'
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - socios-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${CONTAINER_PORT:-3000}']
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  socios-network:
    driver: bridge
